<div class="student-info">
    <h1 class="title"><?= __('Student Form') ?></h1>
    <form class="form" action="" method="post">
        <fieldset class="fieldset">
            <div class="field">
                <label class="label"><?= __('First Name') ?></label>
                <input type="text" class="input-text" name="sfirstname">
            </div>
            <div class="field">
                <label class="label"><?= __('Last Name') ?></label>
                <input type="text" class="input-text" name="slastname">
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button class="action primary" type="submit" title="Submit Student Form">
                    <span><?= __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
