<div class="student-info">
    <h1 class="title"><?= __('Student Form') ?></h1>
    <form id="student_info" class="form" action="" method="post">
        <fieldset class="fieldset">
            <div class="field">
                <label class="label"><?= __('First Name') ?></label>
                <input type="text" class="input-text required-entry" name="fname">
            </div>
            <div class="field">
                <label class="label"><?= __('Last Name') ?></label>
                <input type="text" class="input-text required-entry" name="lname">
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button class="action primary" type="submit" title="Submit Student Form">
                    <span><?= __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<table class="student-list">
    <tr>
        <th><?= __('First Name') ?></th>
        <th><?= __('Last Name') ?></th>
    </tr>
    <tr>
        <td>Vikram</td>
        <td>Kumar</td>
    </tr>
</table>

<script type="text/x-magento-init">
    {
        "#student_info": {
            "validation": {}
        }
    }
</script>
